# Generated by Django 3.2.7 on 2021-12-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20211230_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='noc',
            field=models.IntegerField(default=0),
        ),
    ]
